version: '3.8'
services:
  java-app:
    build: .
    container_name: cloudService
    environment:
      - CONNECTION_URL=http://assessment:8080
    networks:
      - my_network

networks:
  my_network:
    external: true