name: build-push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Pull Assessment Docker Image
        run: docker pull mrksdh/assessment

      - name: Install cUrl
        run: |
          sudo apt-get update && sudo apt-get install -y curl

      - name: Create Docker Network
        run: |
          docker network create my_network

      - name: Start Assessment Docker Container
        run: |
          docker run -d --name assessment --network my_network -p 8080:8080 mrksdh/assessment
          sleep 15

      - name: Perform Health Check
        run: |
          curl -f http://localhost:8080/health || exit 1

      - name: Start Java App using Docker Compose
        run: |
          docker-compose up -d