name: build-push

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_service_and_test_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Pull Assessment Docker Image
        run: docker pull mrksdh/assessment

      - name: Install cUrl
        run: |
          sudo apt-get update && sudo apt-get install -y curl

      - name: Create Docker Network
        run: |
          docker network create my_network

      - name: Start Assessment Docker Container
        run: |
          docker run -d --name assessment --network my_network -p 8080:8080 mrksdh/assessment
          sleep 15

      - name: Perform Health Check
        run: |
          curl -f http://localhost:8080/health || exit 1

      - name: Start Java App using Docker Compose
        run: |
          docker compose up -d --wait -w || docker logs cloudservice || exit 1

      - name: Wait for Java App to Start
        run: |
          sleep 10

      - name: Run Java App
        id: run_java_app
        run: |
          # Execute Java app and capture output
          output=$(docker run --network my_network --rm cloudservice)
          echo "Java App Output: $output"
          echo "::set-output name=java_output::$output"
          
          - name: Use Java App Output
            run: |
              echo "The output from the Java app is: ${{ steps.run_java_app.outputs.java_output }}"